version: '3'
services:
  users-service:
    container_name: users-service
    restart: on-failure
    build: ./
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]